config/routes.rb
Molockup10::Application.routes.draw do
  match 'locale' => 'application#locale'

  resources :developer_tools, :reviewer_tools

  post "elements/update" => "elements#update"
  post "elements/delete" => "elements#destroy"
  post "elements/create" => "elements#create"
  post "elements/save" => "elements#save"
  get "elements" => "elements#index"

  get "elements/result/:id" => "elements#result"
  get "elements/result" => "elements#result"

  resources :projects do
    post "update/params" => "projects#updateParams"
    resources :pages do
      post "blocks/update" => "blocks#update"
      post "blocks/delete" => "blocks#destroy"
      post "blocks/create" => "blocks#create"
      post "blocks/save" => "blocks#save"
      get "blocks" => "blocks#index"
    end
  end

  match "/mock/blocks" => "mock#blocks"

  root :to => "contents#main"

end

app/models/element.rb
class Element < ActiveRecord::Base
  belongs_to :element_group
  attr_accessible :css, :element_group, :html, :js, :name, :description, :element_group_id, :initial, :params, :dependencies, :data
  before_save :default_values
  def default_values
    self.css ||= ''
    self.initial ||= '{"w":200,"h":200,"r":{"x":true,"y":true}}'
  end
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  def index
    @groups = ElementGroup.all
    @elements = Element.all.to_json
 end

  def create
    data = params[:data]
    res = {}
    data.each do |obj|
      element = Element.new(obj[1])
      if element.save
        res[obj[0]] = element
      else
        res[obj[0]] = "error"
      end
    end
    render :text => res.to_json
  end

  def update
    data = params[:data]
    res = []
    data.each do |obj|
      element = Element.find(obj[0])
      if (not element.update_attributes(obj[1]))
        res.push({obj[0] => 'error'})
      end
    end
    render :text => res.to_json

  end

  def destroy
    data = params[:data]
    data.each do |obj|
      element = Element.find(obj)
      element.destroy
    end
    render :text => [].to_json
  end

  def result
    if params[:id]
      @element = Element.find(params[:id])
      @element[:css] = add_class_to_css(@element)
      @links = get_links(@element.dependencies)
    end
    render 'result', :layout => false
  end
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/views/elements/_templates.html.erb
<script type="text/template" id="element-item-template">
  <li id="el{{ id }}">
    <a href="#{{ id }}"> {{ name }}
          <span style="display: none;">
            <i class="icon-trash" title="Remove page"></i>
            <i class="icon-pencil" title="Edit page"></i>
          </span>
    </a>
  </li>
</script>

<script type="text/template" id="parameter-item-template">
  <tr><td class="td-first">{{name}}</td><td> <code>{{type}}</code>
      <span style="display: none;">
        <i class="icon-pencil" title="Edit page"></i>
        <i class="icon-trash" title="Remove page"></i>
      </span>
  </td> </tr>
</script>

<script type="text/template" id="dependency-item-template">
  <tr><td><a href="{{dependencies}}" target="_blank">{{dependencies}}</a>
      <span style="display: none;">
        <i class="icon-pencil" title="Edit page"></i>
        <i class="icon-trash" title="Remove page"></i>
      </span>
  </td> </tr>
</script>

app/views/elements/index.html.erb
<% content_for :html_class do %>
    developer
<% end %>

<% content_for :title do %>
  Программист
<% end %>

<% content_for :navigation do %>
    <li xmlns="http://www.w3.org/1999/html"><a href="/">Home</a></li>
    <li><%= link_to "Список проектов", projects_path %></li>
    <li class="active"><%= link_to "Элементы", elements_path %></li>
    <li> <div class="btn btn-info"><i class="icon-play icon-white"></i> Run </div> </li>
<% end %>


<div id="navigation">
  <div>

    <div id="elements">
        <ul class="nav nav-list">
          <li class="nav-header">Some header</li>
          <li class="nav-info">All changes saved</li>
          <div id="element" class="well">
            <h6>Elements List<i class="icon-plus" title="Add page"></i></h6>
            <ul class="nav nav-list">
               <!--список элементов-->
            </ul>
          </div>
        </ul>
    </div>

    <div id="params">
      <ul class="table-list">
        <li id="initial">
          <div>
            <i class="icon-chevron-down"></i>
            Initial
          </div>
          <table class="table table-condensed table-bordered"><tbody>
              <tr><td>width </td><td> <input type="text" name="w" value ="200" class="input-mini input-condensed input-number" /> </td></tr>
              <tr><td>height </td><td> <input type="text" name="h" value ="200" class="input-mini input-condensed input-number" /></td></tr>
              <tr class="initial-resizable"><td>resizable </td><td><input name="r" type="checkbox" checked="checked" /></td></tr>
              <tr><td>&emsp;&emsp;x </td><td><input type="checkbox" name="x" /></td></tr>
              <tr><td>&emsp;&emsp;y </td><td><input type="checkbox" name="y" /></td></tr>
          </tbody></table>
        </li>

        <li id="parameters">
          <div>
            <i class="icon-chevron-down"></i>
            Parameters
            <i class="icon-plus"></i>
          </div>
          <table class="table table-condensed table-bordered"><tbody>
          </tbody></table>
        </li>

        <li id="dependencies">
          <div>
            <i class="icon-chevron-down"></i>
            Dependencies
            <i class="icon-plus"></i>
          </div>
          <table class="table table-condensed table-bordered"><tbody>
          </tbody></table>
        </li>

      </ul>
    </div>

  </div>
</div>

<div id="workspace">
  <div class="leftside">
      <div id="htmlcode">
        <div class="codetype">HTML</div>
        <textarea id="html"></textarea>
      </div>
      <div id="jscode">
        <div class="codetype">javaScript</div>
        <textarea id="js">js</textarea>
      </div>
  </div>
  <div class="rightside">
      <div id="csscode">
        <div class="codetype">css</div>
        <textarea id="css">css</textarea>
      </div>
      <div id="resultcode">
        <div id="result">
          <div class="alert" style="display: none;"> Click "<strong>Run</strong>" button to see result. </div>
          <div class="ajax-loader-container" style="display: none;">
            <div>
                <div class="ajax-loader"></div>
            </div>
          </div>
          <iframe src=""></iframe>
        </div>
      </div>
  </div>
</div>

<div class="templates">
     <%= render "templates" %>
</div>

<script type="text/javascript">
    Mock.data = {
        elements: <%=raw @elements %>
    };
    $(function(){
       Mock.init.developer();
    });
</script>

app/views/elements/result.html.erb
<%= javascript_include_tag "application" %>
<%= stylesheet_link_tag    "application", :media => "all" %>

<style>
    body{
        padding: 0;
    }
    <% if @element != nil %>
        <%=raw @element.css %>
    <% end %>

</style>

<% @links['js'].each do |js| %>
    <script type="text/javascript" src="<%=raw js %>"></script>
<% end %>
<% @links['css'].each do |css| %>
    <link rel="stylesheet" type="text/css" href="<%=raw css %>">
<% end %>
<script>
    Mock = Mock || {};

    Mock.data = {
        elements : [<%=raw @element.to_json%>]
    };

    <% if @element != nil %>
        Mock.F = {
            <%= @element.id %> : function(parameters, data){
                <%=raw @element.js %>
            }
        }
    <% end %>
    $(function(){
        Mock.init.developer_result();
    });


</script>
<div id="workspace">

</div>

<script type="text/template" id="block-template">
  <div class="block">
    <div class="content">
      {{ html }}
    </div>
  </div>
</script>