config/routes.rb
Molockup10::Application.routes.draw do
  match 'locale' => 'application#locale'

  resources :developer_tools, :reviewer_tools

  post "elements/update" => "elements#update"
  post "elements/delete" => "elements#destroy"
  post "elements/create" => "elements#create"
  post "elements/save" => "elements#save"
  get "elements" => "elements#index"

  get "elements/result/:id" => "elements#result"
  get "elements/result" => "elements#result"

  resources :projects do
    post "update/params" => "projects#updateParams"
    resources :pages do
      post "blocks/update" => "blocks#update"
      post "blocks/delete" => "blocks#destroy"
      post "blocks/create" => "blocks#create"
      post "blocks/save" => "blocks#save"
      get "blocks" => "blocks#index"
    end
  end

  match "/mock/blocks" => "mock#blocks"

  root :to => "contents#main"

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :description, :width, :height, :settings
  before_save :default_values
  def default_values
    self.width ||= 800
    self.height ||= 1000
    self.settings ||= '{"snapToGrid":true,"snapToObject":true,"showRuler":true,"showGrid":true,"gridWidth":5,"gridHeight":5}'
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
    render 'new', :layout => true
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to projects_path
    else
      render :action => 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def updateParams
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      render :text => [].to_json
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to projects_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<!-- fixme -->
<% content_for :breadcrumb do %>
  <li><%= link_to "Список проектов", projects_path %><span class="divider">></span></li>
  <li class="active">
  <% if @project.id? %>
    <%= link_to @project.name, edit_project_path(@project.id) %>
  <% else %>
    <%= link_to "Новый проект", new_project_path %>
  <% end %>
  </li>
<% end %>

<%= form_for @project, :html => {:class => "form-horizontal"} do |f| %>
  <fieldset>
    <legend>
      <% if not @project.id? %>
        Создание нового проекта
      <% else %>
        Редактирование проекта
      <% end %>
    </legend>

    <div class="control-group">
      <label class="control-label">Название проекта</label>
      <div class="controls">
        <%= f.text_field :name, :class => "input-xxlarge" %>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">Описание</label>
      <div class="controls">
        <%= f.text_area :description, :class => "input-xxlarge" %>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">Размеры страницы</label>
      <div class="controls">
        <%= f.text_field :width, :class => "input-mini input-number" %>
        x
        <%= f.text_field :height, :class => "input-mini input-number" %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

app/views/projects/index.html.erb
<!-- fixme -->
<% content_for :html_class do %>
    projects
<% end %>

<!-- fixme -->
<% content_for :breadcrumb do %>
  <li class="active"><%= link_to "Список проектов", projects_path %></li>
<% end %>

<h2>Список проектов:</h2>
<ul class="projects">
  <% if not @projects.present? %>
      <div class="empty">Нет проектов</div>
  <% end %>

  <% @projects.each do |project| %>
      <li>
        <%= button_to "", edit_project_path(project.id), :method=> :get, :class => "icon-pencil" %>
        <%= button_to "", project, :confirm => "Are you sure you want to delete?", :method => :delete, :class => "icon-trash" %>
        <%= link_to project.name, project_pages_path(project.id) %>
        <div class="description"><%= project.description %></div>
      </li>
  <%  end %>
  <li><%= link_to "Добавить проект", new_project_path %></li>
</ul>